2024-12-28 19:53:20,957 INFO    MainThread:109186 [wandb_setup.py:_flush():75] Loading settings from /home/awc2159/.config/wandb/settings
2024-12-28 19:53:20,957 INFO    MainThread:109186 [wandb_setup.py:_flush():75] Loading settings from /home/awc2159/projects/MeTra_3D/outputs/2024-12-28/19-53-19/wandb/settings
2024-12-28 19:53:20,957 INFO    MainThread:109186 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'_require_service': 'True'}
2024-12-28 19:53:20,957 WARNING MainThread:109186 [wandb_setup.py:_flush():75] Could not find program at -m classification.training.trainer
2024-12-28 19:53:20,957 INFO    MainThread:109186 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m classification.training.trainer'}
2024-12-28 19:53:20,957 INFO    MainThread:109186 [wandb_init.py:_log_setup():437] Logging user logs to /home/awc2159/projects/MeTra_3D/outputs/2024-12-28/19-53-19/wandb/run-20241228_195320-nmg2x1p4/logs/debug.log
2024-12-28 19:53:20,957 INFO    MainThread:109186 [wandb_init.py:_log_setup():438] Logging internal logs to /home/awc2159/projects/MeTra_3D/outputs/2024-12-28/19-53-19/wandb/run-20241228_195320-nmg2x1p4/logs/debug-internal.log
2024-12-28 19:53:20,958 INFO    MainThread:109186 [wandb_init.py:init():471] calling init triggers
2024-12-28 19:53:20,958 INFO    MainThread:109186 [wandb_init.py:init():474] wandb.init called with sweep_config: {}
config: {}
2024-12-28 19:53:20,958 INFO    MainThread:109186 [wandb_init.py:init():524] starting backend
2024-12-28 19:53:20,962 INFO    MainThread:109186 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-28 19:53:20,965 INFO    MainThread:109186 [wandb_init.py:init():533] backend started and connected
2024-12-28 19:53:20,970 INFO    MainThread:109186 [wandb_init.py:init():597] updated telemetry
2024-12-28 19:53:20,999 INFO    MainThread:109186 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2024-12-28 19:53:24,028 WARNING MsgRouterThr:109186 [router.py:message_loop():76] message_loop has been closed
