2024-12-28 19:49:37,742 INFO    MainThread:104497 [wandb_setup.py:_flush():75] Loading settings from /home/awc2159/.config/wandb/settings
2024-12-28 19:49:37,742 INFO    MainThread:104497 [wandb_setup.py:_flush():75] Loading settings from /home/awc2159/projects/MeTra_3D/outputs/2024-12-28/19-49-36/wandb/settings
2024-12-28 19:49:37,742 INFO    MainThread:104497 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'_require_service': 'True'}
2024-12-28 19:49:37,742 WARNING MainThread:104497 [wandb_setup.py:_flush():75] Could not find program at -m classification.training.trainer
2024-12-28 19:49:37,742 INFO    MainThread:104497 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m classification.training.trainer'}
2024-12-28 19:49:37,742 INFO    MainThread:104497 [wandb_init.py:_log_setup():437] Logging user logs to /home/awc2159/projects/MeTra_3D/outputs/2024-12-28/19-49-36/wandb/run-20241228_194937-3c3ua8sy/logs/debug.log
2024-12-28 19:49:37,742 INFO    MainThread:104497 [wandb_init.py:_log_setup():438] Logging internal logs to /home/awc2159/projects/MeTra_3D/outputs/2024-12-28/19-49-36/wandb/run-20241228_194937-3c3ua8sy/logs/debug-internal.log
2024-12-28 19:49:37,742 INFO    MainThread:104497 [wandb_init.py:init():471] calling init triggers
2024-12-28 19:49:37,742 INFO    MainThread:104497 [wandb_init.py:init():474] wandb.init called with sweep_config: {}
config: {}
2024-12-28 19:49:37,742 INFO    MainThread:104497 [wandb_init.py:init():524] starting backend
2024-12-28 19:49:37,746 INFO    MainThread:104497 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-28 19:49:37,749 INFO    MainThread:104497 [wandb_init.py:init():533] backend started and connected
2024-12-28 19:49:37,752 INFO    MainThread:104497 [wandb_init.py:init():597] updated telemetry
2024-12-28 19:49:37,774 INFO    MainThread:104497 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2024-12-28 19:49:40,802 WARNING MsgRouterThr:104497 [router.py:message_loop():76] message_loop has been closed
