2024-12-28 19:47:50,459 INFO    MainThread:100510 [wandb_setup.py:_flush():75] Loading settings from /home/awc2159/.config/wandb/settings
2024-12-28 19:47:50,459 INFO    MainThread:100510 [wandb_setup.py:_flush():75] Loading settings from /home/awc2159/projects/MeTra_3D/outputs/2024-12-28/19-47-48/wandb/settings
2024-12-28 19:47:50,460 INFO    MainThread:100510 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'_require_service': 'True'}
2024-12-28 19:47:50,460 WARNING MainThread:100510 [wandb_setup.py:_flush():75] Could not find program at -m classification.training.trainer
2024-12-28 19:47:50,460 INFO    MainThread:100510 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m classification.training.trainer'}
2024-12-28 19:47:50,460 INFO    MainThread:100510 [wandb_init.py:_log_setup():437] Logging user logs to /home/awc2159/projects/MeTra_3D/outputs/2024-12-28/19-47-48/wandb/run-20241228_194750-2ba26xgz/logs/debug.log
2024-12-28 19:47:50,460 INFO    MainThread:100510 [wandb_init.py:_log_setup():438] Logging internal logs to /home/awc2159/projects/MeTra_3D/outputs/2024-12-28/19-47-48/wandb/run-20241228_194750-2ba26xgz/logs/debug-internal.log
2024-12-28 19:47:50,460 INFO    MainThread:100510 [wandb_init.py:init():471] calling init triggers
2024-12-28 19:47:50,460 INFO    MainThread:100510 [wandb_init.py:init():474] wandb.init called with sweep_config: {}
config: {}
2024-12-28 19:47:50,460 INFO    MainThread:100510 [wandb_init.py:init():524] starting backend
2024-12-28 19:47:50,463 INFO    MainThread:100510 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-28 19:47:50,466 INFO    MainThread:100510 [wandb_init.py:init():533] backend started and connected
2024-12-28 19:47:50,470 INFO    MainThread:100510 [wandb_init.py:init():597] updated telemetry
2024-12-28 19:47:50,496 INFO    MainThread:100510 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2024-12-28 19:47:53,522 WARNING MsgRouterThr:100510 [router.py:message_loop():76] message_loop has been closed
2024-12-28 19:47:58,518 WARNING MainThread:100510 [wandb_init.py:init():1016] interrupted
Traceback (most recent call last):
  File "/home/awc2159/.conda/envs/metra/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 995, in init
    run = wi.init()
  File "/home/awc2159/.conda/envs/metra/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 629, in init
    run_result = backend.interface.communicate_run(run, timeout=30)
  File "/home/awc2159/.conda/envs/metra/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/awc2159/.conda/envs/metra/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 324, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/awc2159/.conda/envs/metra/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/awc2159/.conda/envs/metra/lib/python3.8/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/awc2159/.conda/envs/metra/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home/awc2159/.conda/envs/metra/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
